src/Entity/Tag.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TagRepository")
 */
class Tag
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Etat;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Project", mappedBy="Tags")
     */
    private $Projects;

    public function __construct()
    {
        $this->Projects = new ArrayCollection();
        $this->Etat = false;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getEtat(): ?bool
    {
        return $this->Etat;
    }

    public function setEtat(bool $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    /**
     * @return Collection|Project[]
     */
    public function getProjects(): Collection
    {
        return $this->Projects;
    }

    public function addProject(Project $project): self
    {
        if (!$this->Projects->contains($project)) {
            $this->Projects[] = $project;
            $project->addTag($this);
        }

        return $this;
    }

    public function removeProject(Project $project): self
    {
        if ($this->Projects->contains($project)) {
            $this->Projects->removeElement($project);
            $project->removeTag($this);
        }

        return $this;
    }

    public function toSerializable(){
        return (object) get_object_vars($this);
    }
}

templates/Data/Tag_HomePage.html.twig
{% extends 'AdminLayout.html.twig' %}

{% block card_title %} Gestionaire : Tag <a class="text-right" href="#" data-toggle="modal" data-target="#form_modal"> <i class="now-ui-icons ui-1_simple-add"></i></a>{% endblock %}

{% block body %}

    <div class="table-responsive">
        <table class="table">
            <thead class=" text-primary">
            <tr>
                <th>
                    id
                </th>
                <th>
                    Nom
                </th>
                <th>
                    Etat
                </th>
                <th class="text-right">
                    Action
                </th>
            </tr></thead>
            <tbody id="liste">
            {% for data in datas %}
            <tr>
                <td>{{ data.id }}</td>
                <td>{{ data.name }}</td>
                <td>
                    {% if data.etat %} <i class="now-ui-icons ui-1_check"></i> {% endif %}
                </td>
                <td class="text-right">
                    <a href="{{ path('Tag_Update', {id:data.id}) }}"> <i class="now-ui-icons ui-1_settings-gear-63"></i></a>
                    <a class="tag_delete_button" onclick="DepletedTag(this, event, '{{ data.name }}');" href="{{ path('Tag_delete',{id:data.id}) }}"> <i class="now-ui-icons ui-1_simple-remove"></i></a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

{% block JS %}
    {{ parent() }}
    <script>

        $(document).ready(function () {
            if ({{ modal }} == 1){
                $('#form_modal').modal();
            }
        });

        function DepletedTag($this, e, $name) {
            console.log($this);
            e.preventDefault();
            var $link = $this.getAttribute('href');
            $('#text_modal').html("Voulez vous vraiment supprimer le tag : " + $name);
            $('#current_modal').modal('toggle');
            $('#valid_supr').click(function () {
                $('#liste').html('<td colspan="4"><img src="{{ asset('img/load.gif') }}" class="rounded mx-auto d-block" style="height: 50px;"></td>');
                $.ajax({
                    method: 'POST',
                    url:$link
                }).done(function (data) {
                    $('#liste').html(data);
                });
            });
        }

    </script>
{% endblock %}

{% block modal_body %}
    {{ form_start(form) }}
    <div class="modal-header">
        <h4 class="modal-title">Nouveau Tag</h4>
    </div>
    <div class="modal-body">
        {{ form_widget(form) }}
    </div>
    <div class="modal-footer">
        <button id="submit" name="submit" class="btn btn-success">Valider</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
    </div>
    {{ form_end(form) }}
{% endblock %}