src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="integer")
     */
    private $Heart;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="Projects")
     */
    private $Tags;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Photo", mappedBy="Project")
     */
    private $photos;

    public function __construct()
    {
        $this->Tags = new ArrayCollection();
        $this->photos = new ArrayCollection();
        $this->Date = new \DateTime();
        $this->Heart = 0;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getHeart(): ?int
    {
        return $this->Heart;
    }

    public function setHeart(int $Heart): self
    {
        $this->Heart = $Heart;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->Tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->Tags->contains($tag)) {
            $this->Tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->Tags->contains($tag)) {
            $this->Tags->removeElement($tag);
        }

        return $this;
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setProject($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->contains($photo)) {
            $this->photos->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getProject() === $this) {
                $photo->setProject(null);
            }
        }

        return $this;
    }
    
    private $files;

    public function setFiles( $file){
        $this->files[] = $file;

        return $this;
    }

    public function getFiles(){
        return $this->files;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use App\Entity\Tag;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;




class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name', TextType::class, [
                'label' => 'Nom du projet',
                'attr' => ['class' => 'form-control']
                ])
            ->add('Description', TextareaType::class, [
                'label' => 'Description du projet',
                'attr' => ['class' => 'form-control']
                ])
            ->add('Tags', EntityType::class,[
                'class' => Tag::class,
                'choice_label' => 'name',
                'multiple'=>'true',
                'label'=> 'Tag du projet',
                'attr' => ['class' => 'form-control']
                ])
            /*->add('files', FileType::class, [
                'data_class' => null,
                'multiple' => 'true',
                'label' => 'Photos du projet',
                'attr' => ['class' => 'form-control']

            ])*/
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php
/**
 * Created by PhpStorm.
 * User: noamcarmi
 * Date: 28/08/2018
 * Time: 17:19
 */

namespace App\Controller;



use App\Entity\Photo;
use App\Entity\Project;

use App\Form\PhotoType;
use App\Form\ProjectType;

use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * Class TagController
 * @Route("/data/project")
 */
class ProjectController extends AbstractController
{

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        return md5(uniqid());
    }

    //ok
    /**
     * @Route("/", name="Project_HomePage")
     */
    public function Project_HomePage(){

        $doc = $this->getDoctrine();

        $data = $doc->getRepository(Project::class)->findAll();

        return $this->render("Data/Project/Projet_Homepage.html.twig",['projects'=>$data]);
    }

    //ok
    /**
     * @Route("/create", name="Project_Create", methods={"POST"})
     */
    public function Project_Create(Request $request){

        $project = new Project();

        $form = $this->get("form.factory")
            ->create(ProjectType::class, $project,
                ['action'=> $this->generateUrl("Project_Create")]
            );
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($project);
            $em->flush();

            return new JsonResponse(["state"=>1, 'confirm'=>1]);
        }
        return $this->render('modal/form.html.twig', ['titre'=> "projet", 'form'=>$form->createView()]);
    }

    //pas test
    /**
     * @Route("/{id}/zoom", name="Project_zoom")
     */
    public function Project_Zoom($id){
        $project = $this->getDoctrine()->getRepository(Project::class)->find($id);
        return $this->render("Data/Project/Project_Zoom.html.twig",["data"=>$project]);
    }

    //ok
    /**
     * @Route("/{id}/remove", name="Project_remove", methods={"POST"})
     */
    public function ProjetRemove($id, Request $request){
        $em = $this->getDoctrine()->getManager();
        $project = $em->getRepository(Project::class)->find($id);
        if ($request->request->has('confirm') && $request->request->get('confirm') == 1){

            foreach ($project->getPhotos() as $photo){
                $this->RemovePhoto($photo);
            }
            $em->remove($project);
            $em->flush();

            return new JsonResponse(["state"=>1, "id"=>$id]);
        }
        else{
            return  $this->render('modal/remove.html.twig', [
                'name'=> $project->getName(),
                'url' => $this->generateUrl("Project_remove", ['id' => $id])
            ]);
        }


    }

    //ok
    private function RemovePhoto($photo){
        $em = $this->getDoctrine()->getManager();

        unlink($this->getParameter('Photo_directory') . '/' . $photo->getFile());
        $em->remove($photo);
        $em->flush();
    }

    /*
     * @param File $photo
     */
    private function AddPhoto($photo, $project){
        $current = new Photo();


        $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

        $file->move(
            $this->getParameter('brochures_directory'),
            $fileName
        );



    }

    //to do
    /**
     * @Route("/{id}/updatePhotos", name="Project_update_photos", methods={"POST"})
     */
    public function ProjectUpdatePhoto($id, Request $request) {
        $em = $this->getDoctrine()->getManager();
        $project = $em->getRepository(Project::class)->find($id);
        $photos = $em->getRepository(Photo::class)->findBy(["Project" => $project]);


        $form = $this->get("form.factory")
            ->create(PhotoType::class, new Photo(),
                ['action'=> $this->generateUrl("Project_update_photos", ['id'=>$id])]
            );

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            var_dump($request->request->get('photos'));
            return new JsonResponse(["state"=>1, 'confirm'=>1]);
        }

        return $this->render('modal/photo-form.html.twig', ["photos"=>$photos, 'id'=>$id, "form"=>$form->createView()]);
    }


}

templates/Data/Project/Photo_form.html.twig
{% extends "AdminLayout.html.twig" %}


{% block body %}
{{  form_start(form) }}

        <div class="form-group">
            {{ form_row(form.file) }}
        </div>

        <input type="submit" value="Envoyer le formulaire">
{{ form_end(form) }}

{% endblock %}

templates/Data/Project/Project_Update.html.twig
{% extends "AdminLayout.html.twig" %}


{% block card_title %} Gestionaire : Project <a class="text-right" href="#" data-toggle="modal" data-target="#modal"> <i class="now-ui-icons ui-1_simple-add"></i></a>{% endblock %}

{% block body %}



{% endblock %}


{% block modal_body %}


{% endblock %}


{% block JS %}
    {{ parent() }}
    <script>
        $(document).ready(function() {
            console.log("ready");
        }
    </script>
{% endblock %}

templates/Data/Project/Project_Zoom.html.twig
<div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">{{ data.name }}</h4><h6 class="modal-title">{{ data.date|date("m/d/Y") }}</h6>
        </div>
        <div class="modal-body">
            <pre id="text_modal">{{ data.description }}</pre>
            <div class="row
            photo">
                {% for photo in data.photos %}
                    <div class="col-md-4">
                        <img src="{{ asset('uploads/Photo/' ~ photo.file) }}" class="rounded mx-auto d-block">
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
        </div>
    </div>

</div>

templates/Data/Project/Project_liste.html.twig
{% for data in datas %}
    <tr>
        <td>{{ data.id }}</td>
        <td>{{ data.name }}</td>
        <td>{{ data.date|date("m/d/Y") }}</td>
        <td>{{ data.heart}}</td>
        <td>{% for tag in data.tags %} {{ tag.name}} {% endfor %}</td>
        <td>{{ data.photos|length}}</td>
        <td class="text-right">
            <a href="{{ path('Project_zoom',{'id' : data.id}) }}" class="zoom"> <i class="now-ui-icons ui-1_zoom-bold"></i></a>
            <a href=""> <i class="now-ui-icons ui-1_settings-gear-63"></i></a>
            <a href=""> <i class="now-ui-icons ui-1_media-1_camera-compact"></i></a>
            <a class="delete" onclick="DepletedTag(this, event, '{{ data.name }}');" href="{{ path('Project_remove', {'id':data.id}) }}"> <i class="now-ui-icons ui-1_simple-remove"></i></a>
        </td>
    </tr>
{% endfor %}

templates/Data/Project/Projet_Homepage.html.twig
{% extends "AdminLayout.html.twig" %}

{% block css %}
    {{ parent() }}
    <link href="{{ asset('css/dropzone.css') }}" rel="stylesheet">
{% endblock %}

{% block card_title %} Gestionaire : Project <a  class="add_button text-right" href="{{ path('Project_Create') }}"> <i class="now-ui-icons ui-1_simple-add"></i></a>{% endblock %}

{% block body %}


    <div class="table-responsive">
        <table class="table">
            <thead class=" text-primary">
            <tr>
                <th>
                    id
                </th>
                <th>
                    Nom
                </th>
                <th>
                    date
                </th>
                <th>
                    like
                </th>
                <th>
                    tag
                </th>
                <th>
                    photo
                </th>
                <th class="text-right">
                    Action
                </th>
            </tr></thead>
            <tbody id="liste">
            {% for data in projects %}
                <tr>
                    <td>{{ data.id }}</td>
                    <td>{{ data.name }}</td>
                    <td>{{ data.date|date("m/d/Y") }}</td>
                    <td>{{ data.heart}}</td>
                    <td>{% for tag in data.tags %} {{ tag.name}} {% endfor %}</td>
                    <td>{{ data.photos|length}}</td>
                    <td class="text-right">
                        <a href="{{ path('Project_zoom',{'id' : data.id}) }}" class="zoom"> <i class="now-ui-icons ui-1_zoom-bold"></i></a>
                        <a href=""> <i class="now-ui-icons ui-1_settings-gear-63"></i></a>
                        <a onclick="UpdatePhoto(this, event);" href="{{ path('Project_update_photos', {'id':data.id} )}}"> <i class="now-ui-icons media-1_camera-compact"></i></a>
                        <a class="delete" onclick="DeleteProject(this, event);" href="{{ path('Project_remove', {'id':data.id}) }}"> <i class="now-ui-icons ui-1_simple-remove"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}



{% block JS %}
    {{ parent() }}
    <script src="{{ asset('dropzone.js') }}"></script>
    <script>
        $(document).ready(function() {
            console.log("ready");

            $(".add_button").click(function (e) {
                e.preventDefault();
                console.log('homepage');
                let href = $(this).attr('href');
                $.ajax({
                    method : "POST",
                    url: href
                }).done(function ($data) {
                    $('.modal-content').html($data);
                    $('#modal').modal();
                })
            })

        });

        function UpdatePhoto($this, e) {
            e.preventDefault();
            console.log('homepage');
            let href = $($this).attr('href');
            $.ajax({
                method : "POST",
                url: href
            }).done(function ($data) {
                $('.modal-content').html($data);
                $('#modal').modal();
            })
        }

        function DeleteProject($this, e) {
            e.preventDefault();
            $.ajax({
                method : 'POST',
                url : $($this).attr('href')
            }).done(function($data){
                if(typeof $data === 'object' && $data.state === 1) {
                    $('#modal-close').trigger('click');
                    console.log("cigit click");
                    $('.modal-content').html('');
               }else{
                   $('.modal-content').html($data);
                   $('#modal').modal();
                   $('.modal-submit').click(function(e){
                       e.preventDefault();
                       $.ajax({
                           method : "POST",
                           url: $(this).data('href'),
                           data : {'confirm': 1},
                       }).done(function ($data) {
                           if(typeof $data === 'object' && $data.state === 1) {
                               $('#modal-close').trigger('click');
                               console.log("cigit prout");
                               $('.modal-content').html('');
                           }else {
                               $('.modal-content').html("Erreur : veuillez recharger la page.");
                           }
                       })
                   })
               }

            });
        }
    </script>
{% endblock %}